config/routes.rb
Rails.application.routes.draw do

  get "up" => "rails/health#show", as: :rails_health_check
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5, maximum:20}
  validates :description, presence:true, length: {minimum: 5, maximum: 200}
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true,
            length: {minimum: 3, maximum: 20}
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
                  presence: true, 
                  length: {maximum: 50}, 
                  uniqueness: true,
                  format: { with:VALID_EMAIL_REGEX }
  has_many :articles, dependent: :destroy
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # include ApplicationHelper
  def require_user
    if !helpers.logged_in?
      flash[:alert] = "You must be logged in to perform that action!"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:update, :edit, :destroy]

  def show
  end
  def index
    @articles = Article.paginate(page: params[:page], per_page: 2)
  end

  def new
    @article = Article.new
  end

  def edit
  end
  def create
    @article = Article.new(article_params)
    @article.user = helpers.current_user
    if @article.save
      flash[:notice] = "Article saved successfully"
    redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  def update
    if @article.update(article_params)
      flash[:notice]="Article edited successfully"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if @article.user != helpers.current_user && !helpers.current_user.admin?
      flash[:alert]="You can only edit or delete your own article!"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  before_action :require_admin, except: [:index, :show]

  def new
    @category=Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      flash[:notice] = "Category created successfully!"
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 2)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(helpers.logged_in? && helpers.current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if helpers.logged_in?
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user=User.new
  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice]="Logged in successfully!"
      redirect_to user
    else
      flash.now[:alert]="Incorrect login credentials"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index, :new, :create]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def index
    @users=User.all
  end

  def show
    # @articles=@user.articles
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def update 
    if @user.update(user_params)
      flash[:notice]= "#{@user.username}'s details successfully updated"
      redirect_to user_path
    else
      render 'edit'
    end
  end
  def destroy
    @user.destroy
    if helpers.current_user != @user
      flash[:notice] = "Account and all associated articles successfully deleted"
      redirect_to users_path
    else
      flash[:notice] = "Account and all associated articles successfully deleted"
      session[:user_id] = nil
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if @user != helpers.current_user && !helpers.current_user.admin?
      flash[:alert] = "You are not allowed to perform that action!"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_for(user, options = { size: '200x200' })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    robot_url = "https://robohash.org/#{hash}.png/bgset_any?size=#{size}"
    image_tag(robot_url, alt: user.username, class: "rounded-circle shadow mx-auto d-block")
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <%obj.each do |article|%>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
            <div class="card-header fst-italic">
              <%if article.user%>
                by <%= link_to article.user.username, user_path(article.user)%>
              <%end%>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article_path(article), class:"text-success" %></h5>
              <p class="card-text"><%= truncate(article.description, length:100)%></p>
              <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                <%= link_to "View", article_path(article), class:"btn btn-outline-success" %>
                <%= link_to "Edit", edit_article_path(article), class:"btn btn-outline-info"%>
                <%= link_to "Delete", article_path(article), data: {turbo_method: :delete}, class:"btn btn-outline-danger" %>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>
                Created <%= time_ago_in_words(article.created_at)%> ago,
                Edited <%= time_ago_in_words(article.updated_at)%> ago
              </small>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj:@article%>
      <%= form_with(model: @article, local:true, class:"shadow p-3 mb-3 bg-info rounded", data: { turbo: false }) do |f|%>
          <div class="form-group row">
            <%=f.label :title, class:"col-2 col-form-label text-light"%>
            <div class="col-10">
            <%=f.text_field :title, class:"form-control shadow rounded", placeholder: "Title of article"%>
            </div>
          </div>
          <div class="form-group row my-3">
            <%=f.label :description, class:"col-2 col-form-label text-light"%>
            <div class="col-10">
              <%=f.text_area :description, rows:10, class:"form-control shadow rounded", placeholder: "Description of article"%>
            </div>
          </div>
          <div class="form-group row my-3">
            <%=f.label :category, class:"col-2 col-form-label text-light"%>
            <div class="col-10 mt-2">
              <%= select(:category, :category_ids, Category.all.collect { |c| [c.name, c.id] }, 
                { prompt: "Make your selection from the list below (can be empty)", multiple: true }, 
                { class: "form-control" }) %>
            </div>
          </div>
        <div class="form-group row justify-content-center">
          <%=f.submit class:"btn btn-outline-light btn-lg w-auto"%>
        </div>
      <%end%>
      </div>
      <%= link_to "[Cancel edit and return to Articles]", articles_path, class:"d-flex justify-content-center mt-2 text-info" %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container my-5 bg-secondary bg-gradient">
    <h1 class="text-center mt-4">Edit article!</h1>
    <%= render 'form' %>    
</div>

app/views/articles/index.html.erb
<h2 class="text-center mt-4 text-white">Listing all Articles!</h3>
  <div class="container d-flex justify-content-center gap-3 text-white fs-4">
    <%= will_paginate @articles, :container => false %>
  </div>
<%= render 'article', obj:@articles%>
<div class="mb-5 container d-flex justify-content-center fs-4 gap-3 text-white">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<div class="container my-5 bg-secondary bg-gradient">
    <h1 class="text-center mt-4 text-white">Create a new article!</h1>
    <%= render 'form'%>
</div>

app/views/articles/show.html.erb
<div>
  <h2 class="text-center mt-4 text-white"><%=@article.title%></h3>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
            <div class="card-header fst-italic">
              by <%= @article.user.username%>
            </div>
            <div class="card-body">
              <p class="card-text"><%=simple_format(@article.description)%></p>
                <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                  <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-info"%>
                  <%= link_to "Delete", article_path(@article), data: {turbo_method: :delete}, class:"btn btn-outline-danger" %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>
                Created <%= time_ago_in_words(@article.created_at)%> ago,
                Edited <%= time_ago_in_words(@article.updated_at)%> ago
              </small>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/categories/_category.html.erb
<div class="container">
    <%obj.each do |category|%>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
            <div class="card-body">
              <h5 class="card-title"><%= link_to category.name, category_path(category), class:"text-success" %></h5>
            </div>
            <div class="card-footer text-muted">
              <small>
                Created <%= time_ago_in_words(category.created_at)%> ago,
                Edited <%= time_ago_in_words(category.updated_at)%> ago
              </small>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/categories/index.html.erb
<h2 class="text-center mt-4 text-white">Categories Listing</h2>
<div class="container d-flex justify-content-center gap-3 text-white fs-4">
  <%= will_paginate @categories, :container => false %>
</div>
  <%= render 'category', obj:@categories%>
<div class="mb-5 container d-flex justify-content-center fs-4 gap-3 text-white">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<div class="container my-5 bg-secondary bg-gradient">
    <h1 class="text-center mt-4">Create a new category!</h1>
    <div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj:@category%>
      <%= form_with(model: @category, local:true, class:"shadow p-3 mb-3 bg-info rounded", data: { turbo: false }) do |f|%>
          <div class="form-group row my-5">
            <%=f.label :name, "Category name", class:"col-2 col-form-label text-light"%>
            <div class="col-10">
            <%=f.text_field :name, class:"form-control shadow rounded", placeholder: "Enter a name"%>
            </div>
          </div>
        <div class="form-group row justify-content-center">
          <%=f.submit class:"btn btn-outline-light btn-lg w-auto"%>
        </div>
      <%end%>
      </div>
      <%= link_to "[Return to articles listing]", articles_path, class:"btn btn-outline-info w-25 mt-2" %>
  </div>
</div>

</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4 text-white">Category: <%= @category.name%></h1>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white text-center py-3">
  © 2025 <%= link_to "Asn-Teknologies", "https://mern-nganje-portfolio.netlify.app/" %>. All rights reserved.
</footer>

app/views/layouts/_messages.html.erb
<div class="container ">
  <% flash.each do |name, msg|%>
    <div class="alert alert-<%= name == "notice"? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%=msg%>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <%end%>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-black">
  <div class="container bg-black p-10">
    <%= link_to 'ALPHA BLOG', root_path, class:"navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Bloggers', users_path, class:"nav-link text-white" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? %>
              <%= link_to 'Create new article', new_article_path, class:"dropdown-item" %>
            <% end %>
            <%= link_to 'View articles', articles_path, class:"dropdown-item" %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? && current_user.admin?%>
              <%= link_to 'Create new category', new_category_path, class:"dropdown-item" %>
            <% end %>
            <%= link_to 'View categories', categories_path, class:"dropdown-item" %>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
            </a>
              <ul class="dropdown-menu">
                <%= link_to 'View your profile', current_user, class:"dropdown-item" %>
                <%= link_to 'Edit your profile', edit_user_path(current_user), class:"dropdown-item" %>
                <%= link_to 'Delete profile',
                    user_path(current_user),
                    class:"dropdown-item text-danger",
                    data: {turbo_method: :delete,
                          turbo_confirm: "Are you sure?"
                    }
                %>
            </ul>
          </li>
          <li class="nav-item">
          <%= link_to 'Logout', logout_path, class:"nav-link text-white", data: {turbo_method: :delete} %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class:"nav-link text-white" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class:"nav-link text-white" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success text-white" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <main class="flex-grow-1 bg-secondary bg-gradient">
      <%= render 'layouts/navigation'%>
      <%= render 'layouts/messages'%>
      <%= yield %>
    </main>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <h1 class="text-primary">About Page</h1>
    <p>
        <%= link_to "Articles Listing", articles_path%>
    </p>
    <p>
        <%= link_to "Home", root_path%>
    </p>
</div>

app/views/pages/home.html.erb
<div class="container my-5 bg-secondary bg-gradient">
    <div class="p-5 text-center rounded-3 shadow bg-black text-white">
        <h1 class="display-4">Welcome to Alpha-Blog</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>Use it to showcase something important.</p>
        <%=link_to "Sign up!", signup_path, class:"btn btn-success btn-lg" %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors occurred!</h4>
    <ul>
      <%obj.errors.full_messages.each do |message| %>
        <li>
          <%=message%>
        </li>
      <%end%>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <%end%>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj:@user%>
      <%= form_with(model: @user, local:true, class:"shadow p-3 mb-3 bg-info rounded", data: { turbo: false }) do |f|%>
          <div class="form-group row">
            <%=f.label :username, class:"col-2 col-form-label text-light"%>
            <div class="col-10">
            <%=f.text_field :username, class:"form-control shadow rounded", placeholder: "Enter username"%>
            </div>
          </div>
          <div class="form-group row my-3">
            <%=f.label :email, class:"col-2 col-form-label text-light"%>
            <div class="col-10">
              <%=f.email_field :email, class:"form-control shadow rounded", placeholder: "Enter email"%>
            </div>
          </div>
          <div class="form-group row my-3">
            <%=f.label :password, class:"col-2 col-form-label text-light"%>
            <div class="col-10">
              <%=f.password_field :password, class:"form-control shadow rounded", placeholder: "Choose a password"%>
            </div>
          </div>
        <div class="form-group row justify-content-center">
          <%=f.submit(@user.new_record? ? 'Sign up': 'Update Account', class:"btn btn-outline-light btn-lg w-auto")%>
        </div>
      <%end%>
      </div>
      <%= link_to "Login", login_path, class:"btn btn-outline-info w-25 mt-2" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container my-5 bg-secondary bg-gradient">
    <h1 class="text-center mt-4">Edit your profile!</h1>
    <%= render 'form'%>
</div>

app/views/users/index.html.erb
<div>
  <h2 class="text-center mt-2 text-white">Alpha Bloggers!</h3>
  <div class="container">
    <%@users.each do |user|%>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-2">
        <div class="card text-center shadow mb-2 bg-body rounded">
            <div class="card-header fst-italic mb-2">
              <%= link_to user.username, user %>
            </div>
            <div>
              <%= link_to avatar_for(user), user %>
            </div>
            <p class="mt-1"><%=pluralize(user.articles.count, 'article')%></p>
            <div class="card-body">
              <%= link_to "View Profile", user_path(user), class:"btn btn-outline-success" %>
              <% if logged_in? %>
                <% if user == current_user %>
                  <%= link_to "Edit Profile", edit_user_path(user), class:"btn btn-outline-info"%>
                <% end %>
                <% if current_user.admin? %>
                  <%= link_to "Delete profile",
                            user_path(user),
                            class:"btn btn-outline-danger",
                            data: {turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                            }
                  %>
                <% end %>
              <% end %>
            <div class="card-footer text-muted mt-2">
              <small>
                Joined <%= time_ago_in_words(user.created_at)%> ago,
              </small>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/users/new.html.erb
<div class="container my-5 bg-secondary bg-gradient">
    <h1 class="text-center mt-4">Sign Up for Alpha-Blog!</h1>
    <%= render 'form'%>
</div>

app/views/users/show.html.erb
<div class="container my-5 bg-secondary bg-gradient">
    <h1 class="text-center mt-4 text-white"><%= @user.username%>'s profile</h1>
    <%= avatar_for @user%>
    <div class="text-center mt-4">
        <% if logged_in? && @user == current_user %>
            <%= link_to 'Edit your Profile', edit_user_path(@user), class:"btn btn-outline-info" %>
        <% end %>
    </div>  
    <h2 class="text-center mt-4">Articles</h2>
    <%= render 'articles/article', obj:@user.articles%>
</div>